/**
 * Core page registry.
 * These are upstream-owned page components exported by stable name.
 * DO NOT edit this file — it is owned by the upstream project.
 *
 * To override a page, add it to: web/theme/overrides/pages/index.ts
 */

export { default as HomePage } from "./HomePage";
