# build
FROM golang:1.26 AS build
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api

# run
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=build /app/api /api
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/api"]
