/**
 * Core component registry.
 * These are upstream-owned components exported by stable name.
 * DO NOT edit this file — it is owned by the upstream project.
 *
 * To override a component, add it to: web/theme/overrides/components/index.ts
 */

export { StorefrontHeader } from "@/components/storefront-header";
export { StorefrontFooter } from "@/components/storefront-footer";
