/**
 * ui(name) — component/page override resolver.
 * DO NOT edit this file — it is owned by the upstream project.
 *
 * Usage:
 *   const Header = ui("StorefrontHeader");
 *   return <Header isAuthenticated={true} />;
 *
 *   const HomePage = ui("HomePage");
 *   return <HomePage />;
 *
 * Lookup order:
 *   1. theme/overrides/pages/<Name>
 *   2. core/pages/<Name>
 *   3. theme/overrides/components/<Name>
 *   4. core/components/<Name>
 */

import React from "react";
import * as CorePages from "@/core/pages/index";
import * as CoreComponents from "@/core/components/index";
import * as OverridePages from "@/theme/overrides/pages/index";
import * as OverrideComponents from "@/theme/overrides/components/index";

const overridePagesMap = OverridePages as Record<string, React.ComponentType<any>>;
const corePagesMap = CorePages as Record<string, React.ComponentType<any>>;
const overrideComponentsMap = OverrideComponents as Record<string, React.ComponentType<any>>;
const coreComponentsMap = CoreComponents as Record<string, React.ComponentType<any>>;

export function ui(name: string): React.ComponentType<any> {
  const component =
    overridePagesMap[name] ??
    corePagesMap[name] ??
    overrideComponentsMap[name] ??
    coreComponentsMap[name];

  if (!component) {
    throw new Error(
      `[ui] No component found for "${name}". ` +
        `Check web/core/pages/index.ts or web/core/components/index.ts for available names.`
    );
  }
  return component;
}
