/**
 * ui(name) — component override resolver.
 * DO NOT edit this file — it is owned by the upstream project.
 *
 * Usage:
 *   const Header = ui("StorefrontHeader");
 *   return <Header isAuthenticated={true} />;
 */

import React from "react";
import * as CoreComponents from "@/core/components/index";
import * as Overrides from "@/theme/overrides/components/index";

const overrideMap = Overrides as Record<string, React.ComponentType<any>>;
const coreMap = CoreComponents as Record<string, React.ComponentType<any>>;

export function ui(name: string): React.ComponentType<any> {
  const component = overrideMap[name] ?? coreMap[name];
  if (!component) {
    throw new Error(
      `[ui] No component found for "${name}". ` +
        `Check web/core/components/index.ts for available names.`
    );
  }
  return component;
}
